Fix ceilometer-agent blocking and neutron-gateway
openstack-charmers/openstack-on-lxd pull request #64
Opened 2019-05-14 14:34 UTC by zzehring

The following adjustments to the bionic-queens bundle solve
a few issues encountered when deploying on LXD. Ceilometer-agent
was being blocked due to missing Messaging relation. Also,
neutron-gateway resulted in an error state due to the sysctl error
as well as the data-port using a device that didn't exist.

- Add ceilometer-agent relation with rabbitmq-server
- Change neutrongw config sysctl to blank string
- Change neutrongw config data-port to br-ex:eth0 br-data:eth0

2019-05-14 14:41 UTC, zzehring commented
Looks like the other PR is needed to merge for Travis CI to work here.

2019-05-14 14:44 UTC, andrewdmcleod commented
Has this been tested? I don't think using eth0 will work as the port has to be unused, i.e. not have an ip address assigned to it

2019-05-14 14:47 UTC, zzehring commented
I was iffy on the data-port setting as well, but this was the only config that worked to have a successful deployment. Having eth1 was not working for me at all (following that OpenStack-on-LXD guide. I could remove that part and leave the other 2 changes (as I know those do break it).

2019-05-14 14:48 UTC, andrewdmcleod requested changes
data-port should not be primary system interface

2019-05-14 18:46 UTC, zzehring commented
Removed data-port change and tested again. Bundle deployed fine.

2019-05-15 07:00 UTC, andrewdmcleod approved these changes

2019-05-15 07:03 UTC, andrewdmcleod commented
Ok, looks good - however, before we can merge, the travis check will need to pass. If you view the details of the jobs you can find the job log which describes the error as something like "too much diff for openrc"

This is because we have a primary source location for openrc and other tools. To rectify this, you need to run "tox -e sync-tools" and add it to your PR (see tox.ini for details of sync-tools)

2019-05-17 11:00 UTC, merged