fix the `OS_AUTH_PROTOCOL` setting on https
openstack-charmers/openstack-on-lxd pull request #79
Opened 2020-09-16 13:29 UTC by r-f-g

If the variable _root_ca is not present, then this condition should not
set OS_AUTH_PROTOCOL to https.

closes: #78

2020-09-16 14:07 UTC, AurelienLourot commented
The CI is failing because now the file you touched differs from https://github.com/openstack-charmers/openstack-charm-testing . You'll have to get that change landed there first. Thanks!

2020-09-17 08:35 UTC, r-f-g commented
[PR](https://github.com/openstack-charmers/openstack-charm-testing/pull/67) to fix a failed CI.

2020-09-17 08:46 UTC, AurelienLourot requested changes

2020-09-17 08:46 UTC, AurelienLourot commented on openrcv3_domain
> +if [ ! -s $_root_ca ]; then
Can you explain the rationale behind this change? The new code reads like "if the file _root_ca doesn't exist, let's use https" and that doesn't make sense to me. What am I getting wrong? Thanks!

https://www.gnu.org/software/bash/manual/html_node/Bash-Conditional-Expressions.html

2020-09-17 08:47 UTC, AurelienLourot commented on openrcv3_domain
> +if [ ! -s $_root_ca ]; then
ah I understand now, what you want is "if string not empty and if file exists", correct?

2020-09-17 12:03 UTC, AurelienLourot requested changes

2020-09-17 12:03 UTC, AurelienLourot commented on openrcv3_domain
> +if [ ! -v $_root_ca -a -s $_root_ca ]; then
`-v` isn't valid for `[`
`[` is an alias for test, and https://linux.die.net/man/1/test doesn't contain `-v`

2020-09-17 13:39 UTC, AurelienLourot commented
This now looks good to me, thanks! Let's get this change landed on https://github.com/openstack-charmers/openstack-charm-testing/pull/67 first

2020-09-17 14:01 UTC, AurelienLourot approved these changes

2020-09-17 14:04 UTC, AurelienLourot commented
(did a force-push to re-trigger the CI)

2020-09-17 14:05 UTC, merged